### ISSUE TITLE
[feature] implement similarity metrics for all kind of sequences, not only strings

### ISSUE THREAD

**Issue by lovasoa** [dguo/strsim-rs#29]
It would be nice to be able to use this library to compute similarity metrics between different types, and not only strings.

For instance, one could compute the edit distance between two files by comparing their bytes, even if they do not contain valid UTF8 and thus cannot be represented as rust strings.

**Comment by gchers** [comment]
Hi @dguo and @lovasoa,

What's the status with this PR? It'd be a very valuable feature to have, since these similarity metrics are useful also for non-string input. Also, AFAIK, this would make it the first Rust crate implementing them for generic slice-like inputs.

A note on the current implementation. @lovasoa implemented this feature by creating new `*_generic()` functions, and using them to wrap around the original ones with `str` input.

If I may, could I suggest to consider the following alternative solution:
```rust
fn distance<T>(x1: &[T], x2: &[T]) -> usize {
    // compute distance
}
```
This would be more standard in Rust, give a cleaner interface, and probably be easier to maintain. Furthermore, it seems to me that internally the distance functions already work on `char` slices/iters rather than `str`.
On the downside, this breaks the current API: it would require to call the functions as`distance("asdf".as_bytes(), "adss".as_bytes())` (instead of the current `distance("asdf", "adss")`).
(It'd be nice to have a generic that works on both `&str` and `&[T]` for some type `T`, but I don't think it's possible.)

It's also possible to achieve a similar result by using traits, which would allow writing `"asdf".distance("adss")`, although I appreciate this would be too big of a change for the API.


Regardless the implementation details, I was wondering if you could discuss/accept this PR?

**Comment by lovasoa** [comment]
@gchers Unfortunately, I think that this library is dead :/ The most recent commit was in october 2018.

Concerning your proposition: it would remove a whole range of use cases that are possible with my current implementation. `IntoIterator<Item=T>` is very different from `&[T]`, and your proposition would make it impossible to compute the distances in a streaming fashion.

**Comment by gchers** [comment]
> @gchers Unfortunately, I think that this library is dead :/ The most recent commit was in october 2018.

Well, on https://crates.io it seems the most popular among its peer projects (https://crates.io/search?q=levenshtein), and still it's the most recently updated (excluding https://github.com/febeling/edit-distance, which although is not as complete).

> Concerning your proposition: it would remove a whole range of use cases that are possible with my current implementation. `IntoIterator<Item=T>` is very different from `&[T]`, and your proposition would make it impossible to compute the distances in a streaming fashion.

Yes, you're right. I was looking for a way that didn't require the duplication `distance()` `distance_generic()`, but I suppose that's fine.

**Comment by lovasoa** [comment]
Let's hope @dguo will come back online sometime soon !

**Comment by dguo** [comment]
Thanks for bringing this back to my attention @gchers, and sorry for the long delay, @lovasoa. I've been working on other things, but this library is not dead. I'll review the PR within the next day or two.

A preliminary question though: what are some specific use cases for comparing non-string input? I've only ever read about these metrics being used for strings.

**Comment by lovasoa** [comment]
Thank you very much for your work on this project @dguo ! One use case for non-string distances in to compare raw bytes. This would allow the computation of distances between binary files. Another use for these generic functions is to start computing distances before having received a the whole input. One could also use these algorithms in bioinformatics on DNA data, for instance.

**Comment by gchers** [comment]
Just to chip in from my experience, I've also used them (and seen them being used) for modelling the distance between network traffic traces (e.g., [1,2]).
So not only these generic methods will be useful for `T=u8` (i.e., binary files), but also for much stranger object types.

----

[1] https://dl.acm.org/citation.cfm?doid=2382196.2382260
[2] https://www.degruyter.com/downloadpdf/j/popets.2017.2017.issue-4/popets-2017-0046/popets-2017-0046.pdf

**Comment by lovasoa** [comment]
@dguo did you have time to take a look ?

**Comment by dguo** [comment]
Just left a review with some minor suggestions. Sorry, I got really sick and spent the last week recovering. Back to normal now!

**Comment by lovasoa** [comment]
I hope you are better @dguo ! I updated my PR with respect to your comments.

**Comment by lovasoa** [comment]
@dguo can you please make a new release on crates.io ?

**Comment by dguo** [comment]
Thanks for everyone's patience! It's on crates.io now as [v0.9.0](https://crates.io/crates/strsim/0.9.0).
